name: Call BPMN-validate workflow

on:
  push:
    branches:
      - main

jobs:
  call-BPMN-validate-workflow:
    permissions:
      contents: read
    uses: KristofferHogberg/validate-bpmn-action/.github/workflows/validate-bpmn.yml@main
    with:
      bpmn-file-path: 'BPMN/demo-process.bpmn'
      custom-rules-folder: 'custom_rules'
      bpmnlintrc-path: 'BPMN/.bpmnlintrc'
