name: Call BPMN-validate workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: KristofferHogberg/validate-bpmn-action/.github/workflows/validate-bpmn.yml@main
    with:
      bpmn-file: 'BPMN/invalid-model.bpmn'
      custom-rules-folder: 'custom_rules/'
      bpmnlintrc-path: '.bpmnlintrc'
