name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call_bpmn_validate_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: KristofferHogberg/validate-bpmn-action@v.1.0.0
        with:
          bpmn-files-path: 'BPMN'  # Adjust paths accordingly
          custom-rules-folder: 'custom_rules'
          bpmnlintrc-path: 'BPMN/.bpmnlintrc'
