name: Another Workflow

on:
  push:
    branches:
      - main

jobs:
  run_bpmnlint_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger BPMNLint Validation
        uses: KristofferHogberg/call-validate-bpmn-workflow/.github/workflows/validate-bpmn.ymll@main
        with:
          bpmn-folder: 'BPMN/'
          custom-rules-folder: 'custom_rules/'
          bpmnlintrc-path: '.bpmnlintrc'
