name: Validate BPMN process models

on:
   workflow_dispatch:

jobs:
   call_bpmn_validate_workflow:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Validate BPMN process models
           uses: apendo-c8/validate-bpmn-models@v1
           with:
              bpmn-files-path: 'BPMN'
              custom-rules-folder: 'custom_rules'
