name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: KristofferHogberg/call-validate-bpmn-workflow/.github/workflows/validate-bpmn.ymll@main
    with:
      bpmn-folder: 'BPMN/'
      custom-rules-folder: 'custom_rules/'
      bpmnlintrc-path: '.bpmnlintrc'
