name: Another Workflow

on:
  push:
    branches:
      - main

jobs:
  run_bpmnlint_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger BPMNLint Validation
        uses: ./.github/workflows/bpmnlint-validation.yml
        with:
          bpmn-folder: 'BPMN/'
          custom-rules-folder: 'custom_rules/'
          bpmnlintrc-path: '.bpmnlintrc'
