name: Call BPMN-validate workflow

on:
  push:
    branches:
      - main

jobs:
  call-BPMN-validate-workflow:
    permissions:
      contents: read
    uses: apendo-c8/validate-bpmn-model/.github/workflows/validate-bpmn-model@main.yml
    with:
      bpmn-file-path: 'BPMN/demo-process.bpmn'
      custom-rules-folder: 'custom_rules/'
      bpmnlintrc-path: 'BPMN/.bpmnlintrc'
