name: Validate BPMN process models

on:
   workflow_dispatch:

jobs:
   call_bpmn_validate_workflow:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@main

         # Set up NodeJs
         - name: Set up NodeJs
           uses: actions/setup-node@v3
           with:
              node-version: 18.17.0

         # Install bpmnlint
         - name: Install bpmnlint
           run: npm install -g bpmnlint

         - name: Validate BPMN process models
           uses: KristofferHogberg/validate-bpmn-action@main
           with:
              bpmn-files-path: 'BPMN' 
              custom-rules-folder: 'custom_rules'
              bpmnlintrc-path: 'BPMN/.bpmnlintrc'
              node-version: '18.17.0'
